### PR TITLE
 Add optional support for systemd socket activation

### PR DESCRIPTION
**Pull request by andrewshadura**
This commit adds systemd socket activation and notification interface. Please consider merging it.

(This PR is a duplicate of #6 after I have accidentally closed it)

### CODE REVIEW

**Comment by wertarbyte** [comment]
I cherry-picked the top commit, but I cannot test it since I do not run systemd. Can you test the branch systemd?

**Comment by andrewshadura** [comment]
Well, if you cherry-picked it it should work (as I checked, the diff seems to be the same). The only note is that probably it's worth changing my email from my personal address to andrew.shadura@collabora.co.uk.

**Comment by andrewshadura** [comment]
@wertarbyte, anything on this since then?

**Comment by andrewshadura** [comment]
@wertarbyte, ping again.

**Comment by wertarbyte** [comment]
I cherry-picked your change in my local build branch, so it'll be included in the new packet :-)
I just wasn't able to push it to github for now since I cannot reach the right SSH key at the moment.

**Comment by andrewshadura** [comment]
Thanks! In any case, I have rebased the commit and edited S-O-B and the author field. If you wish, pull this commit instead :)

**Comment by andrewshadura** [comment]
Merged as 9a760dcc7c9a8c7859d7bde5bd3dfc4c06ebe17d.

**Comment by andrewshadura** [comment]
However, the Debian packaging doesn't install the systemd unit files, could you please fix that?

**Comment by wertarbyte** [comment]
I've created the triggerhappy package 0.4.0-2 yesterday which should fix this issue. It's sitting on mentors and should will be uploaded later today :-)

**Comment by andrewshadura** [comment]
I have reviewed your packaging, there's a couple more things to fix. I'll post a patch here in a moment.

**Pull request closed without merging**
